import '@/configs/styles/globals.css';

import React from 'react';
import { Oswald } from 'next/font/google';

import { type Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const oswald = Oswald({ subsets: ['latin'], variable: '--font-oswald' });

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${oswald.variable} font-oswald`}>
      <body>{children}</body>
    </html>
  );
}
